<?php

namespace Database\Seeders;

use App\Models\ShippingRate;
use Illuminate\Database\Seeder;

class ShippingRateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rates = [
            // Česká republika - Z-BOX
            [
                'country_code' => 'CZ',
                'country_name' => 'Česká republika',
                'enabled' => true,
                'price_czk' => 99.00,
                'price_eur' => 4.00,
                'applies_to_subscriptions' => true,
                'free_shipping_threshold_czk' => 1000.00,
                'packeta_carrier_id' => 'zpoint',
                'packeta_carrier_name' => 'Zásilkovna Z-BOX',
            ],
            // Slovensko - Packeta SK
            [
                'country_code' => 'SK',
                'country_name' => 'Slovensko',
                'enabled' => true,
                'price_czk' => 150.00,
                'price_eur' => 6.00,
                'applies_to_subscriptions' => true,
                'free_shipping_threshold_czk' => 1500.00,
                'packeta_carrier_id' => '131',
                'packeta_carrier_name' => 'Packeta Slovensko',
            ],
            // Polsko - InPost Paczkomaty
            [
                'country_code' => 'PL',
                'country_name' => 'Polsko',
                'enabled' => true,
                'price_czk' => 180.00,
                'price_eur' => 7.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => 2000.00,
                'packeta_carrier_id' => '3060',
                'packeta_carrier_name' => 'InPost Paczkomaty',
            ],
            // Maďarsko - Packeta Hungary
            [
                'country_code' => 'HU',
                'country_name' => 'Maďarsko',
                'enabled' => true,
                'price_czk' => 200.00,
                'price_eur' => 8.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => 2000.00,
                'packeta_carrier_id' => '4159',
                'packeta_carrier_name' => 'Packeta Maďarsko',
            ],
            // Německo - DHL Packstation
            [
                'country_code' => 'DE',
                'country_name' => 'Německo',
                'enabled' => true,
                'price_czk' => 220.00,
                'price_eur' => 9.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => 2500.00,
                'packeta_carrier_id' => 'de-pp',
                'packeta_carrier_name' => 'DHL Paketshop',
            ],
            // Rakousko - Post AG
            [
                'country_code' => 'AT',
                'country_name' => 'Rakousko',
                'enabled' => true,
                'price_czk' => 220.00,
                'price_eur' => 9.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => 2500.00,
                'packeta_carrier_id' => '4161',
                'packeta_carrier_name' => 'Österreichische Post',
            ],
            // Rumunsko - Packeta Romania
            [
                'country_code' => 'RO',
                'country_name' => 'Rumunsko',
                'enabled' => true,
                'price_czk' => 200.00,
                'price_eur' => 8.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => 2000.00,
                'packeta_carrier_id' => '4162',
                'packeta_carrier_name' => 'Packeta Rumunsko',
            ],
            // Ostatní EU země - zatím vypnuté
            [
                'country_code' => 'BE',
                'country_name' => 'Belgie',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'BG',
                'country_name' => 'Bulharsko',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'HR',
                'country_name' => 'Chorvatsko',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'CY',
                'country_name' => 'Kypr',
                'enabled' => false,
                'price_czk' => 300.00,
                'price_eur' => 12.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'DK',
                'country_name' => 'Dánsko',
                'enabled' => false,
                'price_czk' => 280.00,
                'price_eur' => 11.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'EE',
                'country_name' => 'Estonsko',
                'enabled' => false,
                'price_czk' => 280.00,
                'price_eur' => 11.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'FI',
                'country_name' => 'Finsko',
                'enabled' => false,
                'price_czk' => 300.00,
                'price_eur' => 12.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'FR',
                'country_name' => 'Francie',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'GR',
                'country_name' => 'Řecko',
                'enabled' => false,
                'price_czk' => 280.00,
                'price_eur' => 11.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'IE',
                'country_name' => 'Irsko',
                'enabled' => false,
                'price_czk' => 300.00,
                'price_eur' => 12.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'IT',
                'country_name' => 'Itálie',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'LV',
                'country_name' => 'Lotyšsko',
                'enabled' => false,
                'price_czk' => 280.00,
                'price_eur' => 11.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'LT',
                'country_name' => 'Litva',
                'enabled' => false,
                'price_czk' => 280.00,
                'price_eur' => 11.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'LU',
                'country_name' => 'Lucembursko',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'MT',
                'country_name' => 'Malta',
                'enabled' => false,
                'price_czk' => 320.00,
                'price_eur' => 13.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'NL',
                'country_name' => 'Nizozemsko',
                'enabled' => false,
                'price_czk' => 250.00,
                'price_eur' => 10.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'PT',
                'country_name' => 'Portugalsko',
                'enabled' => false,
                'price_czk' => 300.00,
                'price_eur' => 12.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'SI',
                'country_name' => 'Slovinsko',
                'enabled' => false,
                'price_czk' => 220.00,
                'price_eur' => 9.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'ES',
                'country_name' => 'Španělsko',
                'enabled' => false,
                'price_czk' => 280.00,
                'price_eur' => 11.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
            [
                'country_code' => 'SE',
                'country_name' => 'Švédsko',
                'enabled' => false,
                'price_czk' => 300.00,
                'price_eur' => 12.00,
                'applies_to_subscriptions' => false,
                'free_shipping_threshold_czk' => null,
                'packeta_carrier_id' => null,
                'packeta_carrier_name' => null,
            ],
        ];

        foreach ($rates as $rate) {
            ShippingRate::updateOrCreate(
                ['country_code' => $rate['country_code']],
                $rate
            );
        }

        $this->command->info('Shipping rates seeded successfully!');
        $this->command->info('Enabled countries: CZ, SK, PL, HU, DE, AT, RO');
    }
}

