<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    public function index()
    {
        $products = Product::orderBy('sort_order')
            ->orderBy('created_at', 'desc')
            ->paginate(20);

        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        $categories = [
            'espresso' => 'Espresso káva',
            'filter' => 'Filtrovaná káva',
            'decaf' => 'Bezkofeinová káva',
            'accessories' => 'Příslušenství'
        ];
        
        $roasteries = \App\Models\Roastery::orderBy('name')->get();

        return view('admin.products.create', compact('categories', 'roasteries'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'name_en' => 'nullable|string|max:255',
            'description' => 'required|string',
            'description_en' => 'nullable|string',
            'short_description' => 'nullable|string',
            'short_description_en' => 'nullable|string',
            'price' => 'nullable|numeric|min:0',
            'price_eur' => 'nullable|numeric|min:0',
            'stock' => 'nullable|integer|min:0',
            'categories' => 'required|array',
            'categories.*' => 'in:espresso,filter,decaf,accessories',
            'roastery_id' => 'nullable|exists:roasteries,id',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            'is_active' => 'boolean',
            'is_featured' => 'boolean',
            'free_shipping' => 'boolean',
            'is_digital' => 'boolean',
            'exclude_from_discounts' => 'boolean',
            'is_coffee_of_month' => 'boolean',
            'coffee_of_month_date' => 'nullable|string|regex:/^\d{4}-\d{2}$/',
            'sort_order' => 'nullable|integer|min:0',
            // Attributes for coffee products (CZ)
            'origin' => 'nullable|string|max:255',
            'altitude' => 'nullable|string|max:255',
            'processing' => 'nullable|string|max:255',
            'variety' => 'nullable|string|max:255',
            'flavor_notes' => 'nullable|string|max:1000',
            'weight' => 'nullable|integer|min:1',
            'roast_date' => 'nullable|date',
            // Attributes for coffee products (EN)
            'origin_en' => 'nullable|string|max:255',
            'processing_en' => 'nullable|string|max:255',
            'variety_en' => 'nullable|string|max:255',
            'flavor_notes_en' => 'nullable|string|max:1000',
        ]);

        // Slug will be auto-generated by ProductObserver
        $validated['category'] = $validated['categories']; // Store as array
        unset($validated['categories']);
        $validated['is_active'] = $request->has('is_active');
        $validated['is_featured'] = $request->has('is_featured');
        $validated['free_shipping'] = $request->has('free_shipping');
        $validated['is_digital'] = $request->has('is_digital');
        $validated['exclude_from_discounts'] = $request->has('exclude_from_discounts');
        $validated['is_coffee_of_month'] = $request->has('is_coffee_of_month');
        
        // If product is coffee of month, price and stock are optional
        if ($validated['is_coffee_of_month']) {
            $validated['price'] = $validated['price'] ?? 0;
            $validated['stock'] = $validated['stock'] ?? 0;
        }

        // Build attributes array (CZ + EN)
        $attributes = [];
        $attributeFields = ['origin', 'altitude', 'processing', 'variety', 'flavor_notes', 'weight', 'roast_date', 
                           'origin_en', 'processing_en', 'variety_en', 'flavor_notes_en'];
        
        foreach ($attributeFields as $field) {
            if (!empty($validated[$field])) {
                $attributes[$field] = $validated[$field];
            }
        }
        
        if (!empty($attributes)) {
            $validated['attributes'] = $attributes;
        }
        
        // Remove individual attribute fields as they're now in the attributes array
        foreach ($attributeFields as $field) {
            unset($validated[$field]);
        }

        // Handle image upload
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $filename = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path('images/products'), $filename);
            $validated['image'] = 'images/products/' . $filename;
        }

        Product::create($validated);

        return redirect()->route('admin.products.index')
            ->with('success', 'Produkt byl úspěšně vytvořen.');
    }

    public function edit(Product $product)
    {
        $categories = [
            'espresso' => 'Espresso káva',
            'filter' => 'Filtrovaná káva',
            'decaf' => 'Bezkofeinová káva',
            'accessories' => 'Příslušenství'
        ];
        
        $roasteries = \App\Models\Roastery::orderBy('name')->get();

        return view('admin.products.edit', compact('product', 'categories', 'roasteries'));
    }

    public function update(Request $request, Product $product)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'name_en' => 'nullable|string|max:255',
            'description' => 'required|string',
            'description_en' => 'nullable|string',
            'short_description' => 'nullable|string',
            'short_description_en' => 'nullable|string',
            'price' => 'nullable|numeric|min:0',
            'price_eur' => 'nullable|numeric|min:0',
            'stock' => 'nullable|integer|min:0',
            'categories' => 'required|array',
            'categories.*' => 'in:espresso,filter,decaf,accessories',
            'roastery_id' => 'nullable|exists:roasteries,id',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            'is_active' => 'boolean',
            'is_featured' => 'boolean',
            'free_shipping' => 'boolean',
            'is_digital' => 'boolean',
            'exclude_from_discounts' => 'boolean',
            'is_coffee_of_month' => 'boolean',
            'coffee_of_month_date' => 'nullable|string|regex:/^\d{4}-\d{2}$/',
            'sort_order' => 'nullable|integer|min:0',
            // Attributes for coffee products (CZ)
            'origin' => 'nullable|string|max:255',
            'altitude' => 'nullable|string|max:255',
            'processing' => 'nullable|string|max:255',
            'variety' => 'nullable|string|max:255',
            'flavor_notes' => 'nullable|string|max:1000',
            'weight' => 'nullable|integer|min:1',
            'roast_date' => 'nullable|date',
            // Attributes for coffee products (EN)
            'origin_en' => 'nullable|string|max:255',
            'processing_en' => 'nullable|string|max:255',
            'variety_en' => 'nullable|string|max:255',
            'flavor_notes_en' => 'nullable|string|max:1000',
        ]);

        // Slug will be auto-generated/updated by ProductObserver if name or category changed
        $validated['category'] = $validated['categories']; // Store as array
        unset($validated['categories']);
        $validated['is_active'] = $request->has('is_active');
        $validated['is_featured'] = $request->has('is_featured');
        $validated['free_shipping'] = $request->has('free_shipping');
        $validated['is_digital'] = $request->has('is_digital');
        $validated['exclude_from_discounts'] = $request->has('exclude_from_discounts');
        $validated['is_coffee_of_month'] = $request->has('is_coffee_of_month');
        
        // If product is coffee of month, price and stock are optional
        if ($validated['is_coffee_of_month']) {
            $validated['price'] = $validated['price'] ?? 0;
            $validated['stock'] = $validated['stock'] ?? 0;
        }

        // Build attributes array (CZ + EN)
        $attributes = [];
        $attributeFields = ['origin', 'altitude', 'processing', 'variety', 'flavor_notes', 'weight', 'roast_date', 
                           'origin_en', 'processing_en', 'variety_en', 'flavor_notes_en'];
        
        foreach ($attributeFields as $field) {
            if (!empty($validated[$field])) {
                $attributes[$field] = $validated[$field];
            }
        }
        
        if (!empty($attributes)) {
            $validated['attributes'] = $attributes;
        }
        
        // Remove individual attribute fields as they're now in the attributes array
        foreach ($attributeFields as $field) {
            unset($validated[$field]);
        }

        // Handle image upload
        if ($request->hasFile('image')) {
            // Delete old image if exists
            if ($product->image && file_exists(public_path($product->image))) {
                unlink(public_path($product->image));
            }
            
            $file = $request->file('image');
            $filename = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path('images/products'), $filename);
            $validated['image'] = 'images/products/' . $filename;
        }

        $product->update($validated);

        return redirect()->route('admin.products.index')
            ->with('success', 'Produkt byl úspěšně aktualizován.');
    }

    public function destroy(Product $product)
    {
        // Delete product image if exists
        if ($product->image && file_exists(public_path($product->image))) {
            unlink(public_path($product->image));
        }
        
        $product->delete();

        return redirect()->route('admin.products.index')
            ->with('success', 'Produkt byl úspěšně smazán.');
    }
}




