<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    public function index()
    {
        $products = Product::orderBy('sort_order')
            ->orderBy('created_at', 'desc')
            ->paginate(20);

        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        $categories = [
            'espresso' => 'Espresso káva',
            'filter' => 'Filtrovaná káva',
            'decaf' => 'Bezkofeinová káva',
            'accessories' => 'Příslušenství'
        ];
        
        $roasteries = \App\Models\Roastery::orderBy('name')->get();

        return view('admin.products.create', compact('categories', 'roasteries'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'description' => 'required|string',
            'short_description' => 'nullable|string',
            'price' => 'nullable|numeric|min:0',
            'stock' => 'nullable|integer|min:0',
            'categories' => 'required|array',
            'categories.*' => 'in:espresso,filter,decaf,accessories',
            'roastery_id' => 'nullable|exists:roasteries,id',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            'is_active' => 'boolean',
            'is_featured' => 'boolean',
            'is_coffee_of_month' => 'boolean',
            'coffee_of_month_date' => 'nullable|string|regex:/^\d{4}-\d{2}$/',
            'sort_order' => 'nullable|integer|min:0',
            // Attributes for coffee products
            'origin' => 'nullable|string|max:255',
            'altitude' => 'nullable|string|max:255',
            'processing' => 'nullable|string|max:255',
            'variety' => 'nullable|string|max:255',
            'flavor_notes' => 'nullable|string|max:1000',
            'weight' => 'nullable|integer|min:1',
            'roast_date' => 'nullable|date',
        ]);

        // Slug will be auto-generated by ProductObserver
        $validated['category'] = $validated['categories']; // Store as array
        unset($validated['categories']);
        $validated['is_active'] = $request->has('is_active');
        $validated['is_featured'] = $request->has('is_featured');
        $validated['is_coffee_of_month'] = $request->has('is_coffee_of_month');
        
        // If product is coffee of month, price and stock are optional
        if ($validated['is_coffee_of_month']) {
            $validated['price'] = $validated['price'] ?? 0;
            $validated['stock'] = $validated['stock'] ?? 0;
        }

        // Build attributes array
        $attributes = [];
        if (!empty($validated['origin'])) {
            $attributes['origin'] = $validated['origin'];
        }
        if (!empty($validated['altitude'])) {
            $attributes['altitude'] = $validated['altitude'];
        }
        if (!empty($validated['processing'])) {
            $attributes['processing'] = $validated['processing'];
        }
        if (!empty($validated['variety'])) {
            $attributes['variety'] = $validated['variety'];
        }
        if (!empty($validated['flavor_notes'])) {
            $attributes['flavor_notes'] = $validated['flavor_notes'];
        }
        if (!empty($validated['weight'])) {
            $attributes['weight'] = $validated['weight'];
        }
        if (!empty($validated['roast_date'])) {
            $attributes['roast_date'] = $validated['roast_date'];
        }
        
        if (!empty($attributes)) {
            $validated['attributes'] = $attributes;
        }
        
        // Remove individual attribute fields as they're now in the attributes array
        unset($validated['origin'], $validated['altitude'], $validated['processing'], $validated['variety'], $validated['flavor_notes'], $validated['weight'], $validated['roast_date']);

        // Handle image upload
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $filename = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path('images/products'), $filename);
            $validated['image'] = 'images/products/' . $filename;
        }

        Product::create($validated);

        return redirect()->route('admin.products.index')
            ->with('success', 'Produkt byl úspěšně vytvořen.');
    }

    public function edit(Product $product)
    {
        $categories = [
            'espresso' => 'Espresso káva',
            'filter' => 'Filtrovaná káva',
            'decaf' => 'Bezkofeinová káva',
            'accessories' => 'Příslušenství'
        ];
        
        $roasteries = \App\Models\Roastery::orderBy('name')->get();

        return view('admin.products.edit', compact('product', 'categories', 'roasteries'));
    }

    public function update(Request $request, Product $product)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'description' => 'required|string',
            'short_description' => 'nullable|string',
            'price' => 'nullable|numeric|min:0',
            'stock' => 'nullable|integer|min:0',
            'categories' => 'required|array',
            'categories.*' => 'in:espresso,filter,decaf,accessories',
            'roastery_id' => 'nullable|exists:roasteries,id',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            'is_active' => 'boolean',
            'is_featured' => 'boolean',
            'is_coffee_of_month' => 'boolean',
            'coffee_of_month_date' => 'nullable|string|regex:/^\d{4}-\d{2}$/',
            'sort_order' => 'nullable|integer|min:0',
            // Attributes for coffee products
            'origin' => 'nullable|string|max:255',
            'altitude' => 'nullable|string|max:255',
            'processing' => 'nullable|string|max:255',
            'variety' => 'nullable|string|max:255',
            'flavor_notes' => 'nullable|string|max:1000',
            'weight' => 'nullable|integer|min:1',
            'roast_date' => 'nullable|date',
        ]);

        // Slug will be auto-generated/updated by ProductObserver if name or category changed
        $validated['category'] = $validated['categories']; // Store as array
        unset($validated['categories']);
        $validated['is_active'] = $request->has('is_active');
        $validated['is_featured'] = $request->has('is_featured');
        $validated['is_coffee_of_month'] = $request->has('is_coffee_of_month');
        
        // If product is coffee of month, price and stock are optional
        if ($validated['is_coffee_of_month']) {
            $validated['price'] = $validated['price'] ?? 0;
            $validated['stock'] = $validated['stock'] ?? 0;
        }

        // Build attributes array
        $attributes = [];
        if (!empty($validated['origin'])) {
            $attributes['origin'] = $validated['origin'];
        }
        if (!empty($validated['altitude'])) {
            $attributes['altitude'] = $validated['altitude'];
        }
        if (!empty($validated['processing'])) {
            $attributes['processing'] = $validated['processing'];
        }
        if (!empty($validated['variety'])) {
            $attributes['variety'] = $validated['variety'];
        }
        if (!empty($validated['flavor_notes'])) {
            $attributes['flavor_notes'] = $validated['flavor_notes'];
        }
        if (!empty($validated['weight'])) {
            $attributes['weight'] = $validated['weight'];
        }
        if (!empty($validated['roast_date'])) {
            $attributes['roast_date'] = $validated['roast_date'];
        }
        
        if (!empty($attributes)) {
            $validated['attributes'] = $attributes;
        }
        
        // Remove individual attribute fields as they're now in the attributes array
        unset($validated['origin'], $validated['altitude'], $validated['processing'], $validated['variety'], $validated['flavor_notes'], $validated['weight'], $validated['roast_date']);

        // Handle image upload
        if ($request->hasFile('image')) {
            // Delete old image if exists
            if ($product->image && file_exists(public_path($product->image))) {
                unlink(public_path($product->image));
            }
            
            $file = $request->file('image');
            $filename = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path('images/products'), $filename);
            $validated['image'] = 'images/products/' . $filename;
        }

        $product->update($validated);

        return redirect()->route('admin.products.index')
            ->with('success', 'Produkt byl úspěšně aktualizován.');
    }

    public function destroy(Product $product)
    {
        // Delete product image if exists
        if ($product->image && file_exists(public_path($product->image))) {
            unlink(public_path($product->image));
        }
        
        $product->delete();

        return redirect()->route('admin.products.index')
            ->with('success', 'Produkt byl úspěšně smazán.');
    }
}




